---
abstract: 'Documentation generator for ORLite'
author:
  - '|'
build_requires:
  Test::More: 0.47
  Test::Script: 1.03
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: ORLite::Pod
name: ORLite-Pod
no_index:
  directory:
    - inc
    - t
requires:
  Class::Inspector: 1.23
  File::Basename: 0
  File::Path: 2.07
  File::Spec: 0.80
  Getopt::Long: 0
  ORLite: 1.17
  Params::Util: 0.33
  Template: 2.20
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.06
